version: '3'

services:
  rs_server:
    build: ./docker/rs_server
    container_name: rs_server
    volumes:
      - './src/rs_server:/work'
    ports:
      - 55661:55661
    command: /work/exec.sh

  api_server:
    build:
      context: ./docker/api_server
    container_name: api_server
    volumes:
      - './src/api_server:/work'
    ports:
      - "80:8000"
    depends_on:
      - rs_server