services:
  rs_server:
    build: ./docker/rs_server
    container_name: rs_server
    volumes:
      - './src/rs_server:/work'
    ports:
      - "${LOGIN_SERVER_PORT}:${LOGIN_SERVER_PORT}"
    command: python -u -m login.login

  api_server:
    build:
      context: ./docker/api_server
    container_name: api_server
    volumes:
      - './src/api_server:/work'
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - rs_server